<?php

namespace AppBundle\Repository;

/**
 * AirportsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportsRepository extends \Doctrine\ORM\EntityRepository
{
}
