<?php

namespace AppBundle\Repository;

/**
 * AirportGatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportGatesRepository extends \Doctrine\ORM\EntityRepository
{
}
