<?php

namespace AppBundle\Repository;

/**
 * PassengersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengersRepository extends \Doctrine\ORM\EntityRepository
{
}
