<?php

namespace AppBundle\Repository;

/**
 * PassangerDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassangerDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
