<?php

namespace AppBundle\Repository;

/**
 * PlanesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanesRepository extends \Doctrine\ORM\EntityRepository
{
}
