<?php

namespace AppBundle\Repository;

/**
 * PlaneSeatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneSeatsRepository extends \Doctrine\ORM\EntityRepository
{
}
