<?php

namespace AppBundle\Repository;

/**
 * TicketDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
